### ISSUE TITLE
Startup error "Newtonsoft.Json.JsonSerializationException"

### ISSUE THREAD

**Issue by Pulz-TCP** [FragLand/terracord#103]
Error on startup
https://gist.github.com/Pulz-TCP/d07e9f02157404f0dfc1caf920035c4a

### Terracord Version
* 1.2.0

### Terraria/TShock Version
* 1.4.0.5/4.4.0.0

### Discord.Net Version
* Terracord 1.2.0's

### .NET/Mono Version
* 6.8.0.105

### Operating System
* Ubuntu 20.04

**Comment by ldilley** [comment]
Greetings, @Pulz-TCP. This issue occurs when you use the version of `Newtonsoft.Json.dll` included with TShock. Copying `Newtonsoft.Json.dll` from the top-level `TShock` directory to the `ServerPlugins` directory causes this symptom. The solution per `README.md` is to use the instance of `Newtonsoft.Json.dll` supplied with Terracord and place it  into the `ServerPlugins` directory. You could also obtain the DLL elsewhere (such as from NuGet). Discord.Net requires this newer version of `Newtonsoft.Json.dll` (>=11.0.2).

**Comment by Pulz-TCP** [comment]
Ah, I see. It was not for lack of reading the instructions- I did indeed replace the Newtonsoft.Json.dll with the included one- it was because I left the one that came with TShock in the root directory. Issue resolved by overwriting _that_ .dll too with the Terracord one.

Hopefully didn't cause you too much of a headache, I appreciate the response.
