### ISSUE TITLE
Bot emojis don't work well with Discord's dark theme

### ISSUE THREAD

**Issue by Dids** [FragLand/terracord#105]
### Expected Behavior
* Emojis used by the bot should be neutral enough to fit both the light and dark theme, even though the dark theme is more widely used than the light one.

### Actual Behavior/Symptoms
* Emojis used by the bot only work as intended with the light theme, not with the dark theme.

### How to Reproduce Behavior/Symptoms
* Install the bot and see it post messages/emojis in Discord.

### Terracord Version
* https://github.com/FragLand/terracord/commit/d52c708a2413d86e57f67fe2c75f494ba5a3730a

### Output/Screenshot(s)

![Näyttökuva 2020-9-22 kello 14 27 26](https://user-images.githubusercontent.com/3455449/93876792-14334680-fce0-11ea-8c36-6753f66a50f4.png)

**Comment by ldilley** [comment]
Greetings, @Dids.

I fully agree and wish that Discord offered a '+' and '-' emoji with better visibility in dark mode (it is also the theme I've always used). `:heavy_plus_sign:` and `:heavy_minus_sign:` are too dark. The idea to prefix player join/leave messages with this pair of emojis was borrowed from https://github.com/DiscordSRV/DiscordSRV. I was running both DiscordSRV and Terracord for use within the same Discord server at one time. I wanted some uniformity between the #minecraft and #terraria text channels there.

Do you have any suggestions for replacement characters that we could use as a prefix for player join/leave events in Discord?

**Comment by Dids** [comment]
That's a good question, because the default emoji aren't that great.

The only default ones that could work with both themes (and still somewhat make sense) would likely be the `:circle:` emojis, eg. `:green_circle:` for joining and `:orange_circle` (or even `:red_circle`) for leaving?

Ideally though, maybe these could be configurable through `terracord.xml`, so they could be overridden?

**Comment by 06000208** [comment]
I second being able to configure them. With DiscordSRV, I usually use a set of custom emojis designed for the task.

As far as default emojis go, `:white_check_mark:` and `:negative_squared_cross_mark:` match and work on both themes.

**Comment by ldilley** [comment]
The latest commit at the time of this writing, f034948, should do what you want. I'll allow a few days for testing prior to resolving this issue (unless you resolve it first). Please let me know if you need anything else.

**Comment by Dids** [comment]
This solution works absolutely great, thank you! Also added the option to customize these in the Docker container. :)
