### ISSUE TITLE
Players being randomly kicked after joining

### ISSUE THREAD

**Issue by Epikest** [FragLand/terracord#116]
### Expected Behavior
* players are supposed to not get kicked

### Actual Behavior/Symptoms
* players get kicked after a few seconds of joining

### How to Reproduce Behavior/Symptoms
* start server with plugin installed and get players

### Terracord Version
* 1.2.1

### Terraria/TShock Version
* Pre15 1.4.1.2

### Discord.Net Version
* unknown

### .NET/Mono Version
* unknown

### Operating System
* Windows

### Output/Screenshot(s)
![image](https://user-images.githubusercontent.com/45499416/102022667-363ce200-3d80-11eb-848a-682a8277149c.png)

**Comment by ldilley** [comment]
I responded in Discord, @Epikest, but have not seen a reply. To summarize: I need to see console output or the contents of your `terracord.log`. I am looking for any evidence that points to Terracord being the root cause of your disconnects.

**Comment by ldilley** [comment]
User resolved issue by resetting router per a Discord conversation. This is not related to Terracord.
