### ISSUE TITLE
Fully Customizable Messages

### ISSUE THREAD

**Issue by Epikest** [FragLand/terracord#117]
### Feature Description
* complete control over relay, broadcast, leave and join, and chat messages in the config
* support for multiple languages with customizable language files or no language files altogether and just separate editable messages for every language in a different terracord.dll eg: terracordDE.dll terracordEN.dll etc.

**Comment by ldilley** [comment]
I am considering the removal of localization. Localization was originally implemented at the insistence of Visual Studio (the editor recommended moving certain hard-coded strings of text from the source to resource files instead). I used the opportunity to learn how the process works in C#. Rescinding localization would have the following benefits:
* Reduces file clutter (no requirement to have language folders containing separate DLLs in the top-level TShock directory)
* Decreases project complexity (eliminates all existing resource files and the `Properties` directory)
* Allows for greater customization (adds ability to change text without the need to rebuild `Terracord.dll`)

The disadvantages of this change are:
* Users will be required to update their instance of `terracord.xml` (to include all the new options)
* Translations will be lost
* Documentation will need to be updated (specifically, the installation instructions in `README.md`)

The documentation updates will also impact issue #111 and PR #113 which are assigned to @MicaelJarniac. Updating `terracord.xml` should not be a huge problem for users and some folks will likely be fond of the new customization options. Lastly, locale support (currency and number format, etc.) can continue to be maintained in `Config.cs`. Users will be free to translate the text in `terracord.xml` if desired using the new available customization options.

**Comment by ldilley** [comment]
Resolved in #118.
