### ISSUE TITLE
Generate config file if non-existent

### ISSUE THREAD

**Issue by ldilley** [FragLand/terracord#13]
### Feature Description
* If `terracord.xml` is not found, generate a default config file. This can be done after #10 is implemented for `FileNotFoundException`.

**Comment by 84100** [comment]
Hi

I appreciate this probably isn't the best place to ask for help, but I have tried to get this working and not sure where I'm going wrong anymore (spent so much time trying to get this working! :D).  I have built the terracord.dll and put all the bot info in to the config file. I can see terracord executing messages in the Terraria server console, however Discord is empty and doesn't seem to be communicating with Terraria. I would really appreciate your help with this, thanks.
