### ISSUE TITLE
Convert received Discord emojis

### ISSUE THREAD

**Issue by ldilley** [FragLand/terracord#27]
### Feature Description
* Custom emojis appear as `<:emoji_name:1234567890>` when messages from Discord containing them are broadcasted to TShock players. These should be converted to simply `:emoji_name:`. Other standard emojis appear as `**` within the game, `��` on the TShock console, and get rendered as proper Unicode characters in `terracord.log`. How to best handle this still needs to be determined.

**Comment by moisterrific** [comment]
What if you just make emojis not be sent to the in-game chat?

**Comment by ldilley** [comment]
That's also an option and might be easiest. I'd like to look more into how [DiscordSRV](https://github.com/DiscordSRV/DiscordSRV) is handling it. I believe for standard emojis, they're just sending `:smile:` and such through as is. I think they are doing the same for custom emotes (`:whatever:`). Do you remember what some of these look like from within Minecraft, @kyleighd?

**Comment by kyleighd** [comment]
Pretty much the example you've given. They'll simply send as ``:smile:``, or ``:thumbsup:`` . Whatever the name of the emote is, it'll just send it through to Minecraft looking like that.
