### ISSUE TITLE
Add ability to tag people in Discord from Terraria

### ISSUE THREAD

**Issue by kyleighd** [FragLand/terracord#4]
It'd be nice if you could make it so we could tag people using Discord from Terraria using the @ command. :)

**Comment by ldilley** [comment]
Making note of a relevant Discord conversation considering @moisterrific brought up a potential scenario and workaround...

```
🍉 Yesterday at 6:50 PM
what if there’s multiple of the same match?

Maldemort Yesterday at 6:50 PM
two of the same usernames with a different discriminator (#NNNN)

🍉 Yesterday at 6:51 PM
TSAPI has a MultipleMatchError handler you can use
```

**Comment by moisterrific** [comment]
![71D6DAC6-92AA-4014-BF21-66393DCFE141](https://user-images.githubusercontent.com/57187883/72497663-195bff80-37fb-11ea-8862-08880f032a9e.png)
