### ISSUE TITLE
Unhandled Instances

### ISSUE THREAD

**Issue by moisterrific** [FragLand/terracord#41]
## Instance A 
Server enforcing mediumcore or higher characters:
- if a softcore player attempts to join, TShock will "kick" that player
- however, a relay msg is still sent to Discord that looks like this: "has left the server."

## Instance B
Banned player attempting to connect:
- if a banned player attempts to join, TShock will "disconnect" that player
- however, a relay msg is still sent to Discord that looks like this: "`player name` has joined the server."
- it will not show "`player name` has left the server." when it boots the banned player

## Ideally
- no message is relayed to Discord at all for both instances.

**Comment by ldilley** [comment]
Per our earlier Discord discussion today, @moisterrific, is instance B resolved then? You mentioned that bans are now getting relayed properly I believe. For instance A, we can check for a null or empty username and not relay it if either cases are true.

**Comment by ldilley** [comment]
Is this issue resolved with the latest commit (at the time of this reply), 23d806a?

**Comment by moisterrific** [comment]
Can confirm on my end the latest commit now handles both instances properly. 

Difficulty check boot = no msg relayed
Ban check boot = join and leave relayed 

Very nice
