### ISSUE TITLE
How to handle image relays in-game?

### ISSUE THREAD

**Issue by moisterrific** [FragLand/terracord#49]
If a Discord user send an image in the relay channel, it will show up in-game as a blank message. Is this intended? 

(though a quick workaround is to simply disable image permissions in that channel)

**Comment by ldilley** [comment]
After some testing, I've confirmed that any attachments without accompanying text are relayed as seemingly empty messages. Links to images (such as those produced by `/giphy`) work fine and just result in the link being sent.

The fix will require modifying `MessageReceived()` to check if the passed `SocketMessage` object contains an empty message (we should be checking for this anyhow along with `null`). If the aforementioned check yields true, then we do not have to relay the message.

We could additionally check the `SocketMessage` object to see if it contains an attachment. We can then relay a message to players indicating that the message was an attachment. The message relayed could include the file name, the URL, and the optional comment (which would be contained in the message originally sent).

The algorithm for this process would ideally be:

1. Check ALL incoming messages in `MessageReceived()` for attachments.
2. If the message contains an attachment, preserve the comment from `message.Content` if it exists.
3. Get the attachment filename and URL.
4. Set `messageContent` to something like: `[Attachment: <filename> <URL> [comment]]`
5. Relay `messageContent` to TShock.

See the following links for reference:
https://discord.foxbot.me/docs/api/Discord.WebSocket.SocketMessage.html
https://discord.foxbot.me/docs/api/Discord.Attachment.html
