### ISSUE TITLE
Easier Discord user mention

### ISSUE THREAD

**Issue by moisterrific** [FragLand/terracord#50]
Not sure how feasible this would be, but it would be nicer if you didn’t have to type out the full Discord tag to mention a user. 

For example: if the user I want to mention is John, it will match if I type only “Jo”

If there are users named John and Joseph, typing “Jo” will return an error message telling the command user to be more specific.

I just know TShock has this feature for most commands where you can just type a part of a full name and it will match it.

**Comment by ldilley** [comment]
Mention auto-complete would be a neat feature. However, the ambiguous matches may be too inconclusive to be useful. There would be great potential for text channel, role, and user name collisions in larger servers.

**Comment by ldilley** [comment]
I thought about this more while attempting to sleep and came to the conclusion that this would only aggravate the issue you raised about duplicate usernames. I also have an issue with presenting players with error messages for multiple scenarios. The relay should just relay and not complicate message routing by blocking player communication/forcing them to deal with more errors. As a result, I will close this issue out as `wontfix`.
