### ISSUE TITLE
NullRef in OnLeave

### ISSUE THREAD

**Issue by moisterrific** [FragLand/terracord#51]
Not sure why it happened, couldn't reproduce it later myself.

![image](https://user-images.githubusercontent.com/57187883/72672989-9670ba00-3a31-11ea-8b75-13b25681312f.png)

**Comment by ldilley** [comment]
Are you sure this is 23d806a? For starters, that exception was changed to read `Exception caught after player joined or left TShock server: {nre.Message}`. Furthermore, the relevant line has been commented. See line 207 of https://github.com/FragLand/terracord/blob/master/Terracord/Terracord.cs for details. Lastly, there is a `null` check for `eventArgs` in the current commit which should prevent the `NullReferenceException` from being caught.

**Comment by moisterrific** [comment]
Oops I think mine is outdated, I will updated it and re-check.

**Comment by moisterrific** [comment]
yup it's fixed, my mistake forgetting to update to the latest commit.
