### ISSUE TITLE
Put Terracord config and log file into a folder

### ISSUE THREAD

**Issue by moisterrific** [FragLand/terracord#56]
Put terracord.xml and terracord.txt into a tshock\Terracord folder

not a big deal but it would help better organize things for servers that have a lot of plugin configs/logs/database files, etc.

at least according to one of the lead TShock devs
![image](https://user-images.githubusercontent.com/57187883/73001271-303cbc00-3dd0-11ea-8381-e01f8ec33e04.png)

**Comment by moisterrific** [comment]
What some of these other plugins do is 
`public static string ConfigPath = Path.Combine(TShock.SavePath, "Plugin", "PluginConfig.json");`

**Comment by ldilley** [comment]
This was actually the original intent at the project's inception as I was testing read/write paths relative to `Terracord.dll`. The current behavior simply remained after it was discovered that the path relative to `TerrariaServer.exe` worked as intended for configuration file parsing and logging.

This change will require maintainers of existing installations to relocate their configuration file and, optionally, the log file (if they want to append to an extant log). This would additionally necessitate updating the installation instructions in `README.md`.
