### ISSUE TITLE
Terracord Pings Random User

### ISSUE THREAD

**Issue by EMREOYUN** [FragLand/terracord#69]
### Expected Behavior
* I don't know

### Actual Behavior/Symptoms
* Pings random user.

### How to Reproduce Behavior/Symptoms
* Ping someone in Terraria Server

### Terracord Version
* 1.1.0

### Terraria/TShock Version
* 1.3.0.7 / 2.1 (PE)[TShock Zombie]

### Discord.Net Version
* Check from Terracord Release 1.1.0

### .NET/Mono Version
* .NET: 4.0
* Mono: 6.8.0.105

### Operating System
* Windows Server 2012 R2

### Output/Screenshot(s)
![image](https://user-images.githubusercontent.com/35144629/79013546-ab14a800-7b71-11ea-8e69-797e5c8b4d1e.png)

**Comment by ldilley** [comment]
@moisterrific and I have not seen this problem recently. However, it was formerly an issue and I believe it was related to Discord names containing '|' characters. Are you using `Terracord.dll` from the 1.1.0 release zip archive? If so, can you please try using the code from the head of the master branch (commit 0ec40d3) instead?

**Comment by ldilley** [comment]
Closing due to lack of response.
