### ISSUE TITLE
Could this be updated for 1.4 please?

### ISSUE THREAD

**Issue by JMCY26** [FragLand/terracord#70]
I didn't expect it to work but tried to load the available version and it didn't like the discord file on bootup. Is there plans to update this for 1.4 as its very useful.

**Comment by ldilley** [comment]
TShock 4.4.x (for Terraria 1.4) is still in pre-release. I admittedly haven't even tried it yet. I'll leave the bug label for now. However, I am not certain offhand if the API was updated and broke the plugin or if this is a problem on your end perhaps (you have not included any output to help me make that determination). If Terracord is incompatible with TShock 4.4.x, then this issue would be a feature request.

In the case of incompatibility, once a stable release of TShock 4.4.x is available, I will add support for the new version. I'll leave this issue open to track that effort.

**Comment by TakVap** [comment]
Terraria 1.4 did introduce some API changes, attempting to compile Terracord using 'TShock 4.4.0 Pre-release 7' libs results in a few errors:

`Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'Utils' does not contain a definition for 'ActivePlayers' and no accessible extension method 'ActivePlayers' accepting a first argument of type 'Utils' could be found (are you missing a using directive or an assembly reference?)	Terracord	\terracord\Terracord\Command.cs	46	Active`

`Error	CS1061	'Utils' does not contain a definition for 'GetPlayers' and no accessible extension method 'GetPlayers' accepting a first argument of type 'Utils' could be found (are you missing a using directive or an assembly reference?)	Terracord	\terracord\Terracord\Command.cs	47	Active`

`Error	CS1061	'Utils' does not contain a definition for 'ActivePlayers' and no accessible extension method 'ActivePlayers' accepting a first argument of type 'Utils' could be found (are you missing a using directive or an assembly reference?)	Terracord	\terracord\Terracord\Command.cs	53	Active`

`Error	CS1061	'Utils' does not contain a definition for 'ActivePlayers' and no accessible extension method 'ActivePlayers' accepting a first argument of type 'Utils' could be found (are you missing a using directive or an assembly reference?)	Terracord	\terracord\Terracord\Discord.cs	267	Active`

**Comment by moisterrific** [comment]
I believe they moved all that from Utils to TSPlayer...

Edit: nope they just changed the name

**Comment by moisterrific** [comment]
Terracord "works" on the latest TShock pre-release (pre-8 as of this message), but there's this bug where it relays double messages back and fourth lol

gonna try to see if I can fix that

**Comment by moisterrific** [comment]
![image](https://user-images.githubusercontent.com/57187883/82955061-0234d780-9f7c-11ea-974a-aa7b89b073ef.png)
@TakVap You need to make these changes to resolve the compile errors. 

That simply fixes the playerlist command and channel topic, I'm still trying to figure out what's causing the double messages: 
![image](https://user-images.githubusercontent.com/57187883/82955181-41632880-9f7c-11ea-90d2-0ddf04e003cc.png)

**Comment by moisterrific** [comment]
![image](https://user-images.githubusercontent.com/57187883/82955678-5b513b00-9f7d-11ea-936d-30ea2c524393.png)
partial fix for the above issue, however broadcast messages like which boss/event spawned or who died, banner kill counts, etc will not work.

**Comment by moisterrific** [comment]
partial fix for duplicate messages would be to comment out `discord.Send($"**:mega: Broadcast:** {args.Message}");` in Terracord.cs but this also removes server broadcast events (bosses/invasions/banner killcounts,etc) from being relayed.

**Comment by moisterrific** [comment]
Adding this for references, maybe this had something to do with the duplicate messages.
https://github.com/Pryaxis/TShock/commit/83eb707761dc37ebb0b7a90aadeca5896fb568f0
https://github.com/Pryaxis/TShock/commit/5d2945ab1f4be47ab031220ffca9d5ae9d6b4fc4

**Comment by Glendog** [comment]
@moisterrific Is it possible the can provide your discord.cs that compiles?

**Comment by clarg18** [comment]
I changed three instances of `ActivePlayers()` to be `GetActivePlayerCount()` and:

command.cs
```
      if(command.Equals("playerlist", StringComparison.OrdinalIgnoreCase))
      {
        // string playerList = $"{TShock.Utils.GetActivePlayerCount()}/{TShock.Config.MaxSlots}\n\n";
        string playerList = $"{TShock.Utils.GetActivePlayerCount()}/{TShock.Config.MaxSlots}\n\n";
                //foreach(var player in TShock.Utils.GetPlayers(false))

                var players = new List<string>();

                foreach (TSPlayer ply in TShock.Players)
                {
                    if (ply != null && ply.Active)
                    {
                        players.Add(ply.Name);
                    }
                }

                foreach (var player in players)
                {
                    playerList += $"{player}\n";
                }
                
        await CommandResponse(channel, "Player List", playerList).ConfigureAwait(true);
      }
```

It built but I got StackOverflowException

**Comment by ldilley** [comment]
I am working on this now and hope to have a fix committed in <10 hours.

**Comment by ldilley** [comment]
Closing this per #75. I will create a release soon.
