### ISSUE TITLE
Upgraded to 1.20 and receive error on startup

### ISSUE THREAD

**Issue by CTOUT** [FragLand/terracord#94]
### Expected Behavior
* tShock server to load

### Actual Behavior/Symptoms
* tShock server fails to load repeating the following error: - Process is terminated due to StackOverflowException.

### How to Reproduce Behavior/Symptoms
* Upgrade from 1.1 to 1.2, add additional settings to XML file and try starting the server.

### Terracord Version
* 1.2

### Terraria/TShock Version
* 1.4.0.5/4.4.0 Pre-Release 11

### Discord.Net Version
* 2.1.1.0

### .NET/Mono Version
* 4.8

### Operating System
* Windows Server 2019

### Output/Screenshot(s)
![image](https://user-images.githubusercontent.com/22860918/84442266-30c9d800-ac35-11ea-8b58-ce3d67748141.png)

**Comment by ldilley** [comment]
Greetings, @CTOUT. This issue is fixed in `master`. You must've missed a step contained in the 1.2.0 release zip archive's `ReadMe.txt`. The workaround is also referenced in #76. You are missing the `Terracord` directory under `tshock`. `terracord.xml` and `terracord.log` now reside at this path.

**Comment by CTOUT** [comment]
Ah, my apologies.  I had assumed it was just a lift & shift! :)
Thank you.

**Comment by Axieum** [comment]
Hey @CTOUT did this work out for you? I'm running the same versions, and I created the `~/tshock/Terracord/terracord.{xml,log}` files. But when changing directory to `~/tshock` and then running `mono TerrariaServer.exe -worldselectpath ~/worlds` I get the same error you presented...
