### ISSUE TITLE
Add net46 target

### ISSUE THREAD

**Issue by ldilley** [FragLand/terracord#95]
Add additional target `net46` to `Terracord.csproj` since this has been requested by @terraria-by. Discord.Net 2.1.1 requires >=`net46`. This should also allow xUnit tests to work.

**Comment by Dids** [comment]
Just updating here that this actually allowed me to run Terracord with TShock on linux/mono.

Built a [Docker image](https://github.com/Didstopia/terraria-server) that bundles both TShock and Terracord, and so far it seems to be working great!

**Comment by ldilley** [comment]
Thank you for your effort on the Docker image, @Dids. This is good stuff. I'll link to it from Terracord's ReadMe and also include your contribution in the next/subsequent Terracord releases.
